### ISSUE TITLE
[1.8.9] Atum 1.0.6+ crashes

### ISSUE THREAD

**Issue by tildejustin** [VoidXWalker/Atum#12]
Don't have logs because I tested it a long time ago, but it happens across diff mods and fabric and java versions

**Comment by tildejustin** [comment]
```
MultiMC version: 0.7.0-develop-3524


Launched instance in online mode

authserver.mojang.com resolves to:
    [18.67.58.35, 18.67.58.60, 18.67.58.61, 18.67.58.44]

session.minecraft.net resolves to:
    [34.199.236.154, 35.153.153.200, 100.24.172.95]

textures.minecraft.net resolves to:
    [13.224.214.129, 13.224.214.13, 13.224.214.97, 13.224.214.73]

api.mojang.com resolves to:
    [18.160.37.115, 18.160.37.66, 18.160.37.118, 18.160.37.49]


Minecraft folder is:
D:/Games/Minecraft/MultiMC/instances/1.8.9_1/.minecraft


Java path is:
D:/Programs/Program Files/Java/Adoptium 17/bin/javaw.exe


Checking Java version...
Java is version 17.0.4.1, using 64-bit architecture, from Eclipse Adoptium.


Main Class:
  net.fabricmc.loader.impl.launch.knot.KnotClient

Native path:
  D:/Games/Minecraft/MultiMC/instances/1.8.9_1/natives

Libraries:
  D:/Games/Minecraft/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  D:/Games/Minecraft/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  D:/Games/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  D:/Games/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  D:/Games/Minecraft/MultiMC/libraries/com/mojang/netty/1.8.8/netty-1.8.8.jar
  D:/Games/Minecraft/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  D:/Games/Minecraft/MultiMC/libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar
  D:/Games/Minecraft/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  D:/Games/Minecraft/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  D:/Games/Minecraft/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
  D:/Games/Minecraft/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  D:/Games/Minecraft/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  D:/Games/Minecraft/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  D:/Games/Minecraft/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  D:/Games/Minecraft/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  D:/Games/Minecraft/MultiMC/libraries/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar
  D:/Games/Minecraft/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  D:/Games/Minecraft/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  D:/Games/Minecraft/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  D:/Games/Minecraft/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  D:/Games/Minecraft/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  D:/Games/Minecraft/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  D:/Games/Minecraft/MultiMC/libraries/com/mojang/realms/1.7.59/realms-1.7.59.jar
  D:/Games/Minecraft/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  D:/Games/Minecraft/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  D:/Games/Minecraft/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  D:/Games/Minecraft/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  D:/Games/Minecraft/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9-fixed/log4j-api-2.0-beta9-fixed.jar
  D:/Games/Minecraft/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9-fixed/log4j-core-2.0-beta9-fixed.jar
  D:/Games/Minecraft/MultiMC/libraries/tv/twitch/twitch/6.5/twitch-6.5.jar
  D:/Games/Minecraft/MultiMC/libraries/net/fabricmc/intermediary/1.8.9/intermediary-1.8.9.jar
  D:/Games/Minecraft/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar
  D:/Games/Minecraft/MultiMC/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar
  D:/Games/Minecraft/MultiMC/libraries/net/fabricmc/tiny-remapper/0.8.2/tiny-remapper-0.8.2.jar
  D:/Games/Minecraft/MultiMC/libraries/net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar
  D:/Games/Minecraft/MultiMC/libraries/org/ow2/asm/asm/9.3/asm-9.3.jar
  D:/Games/Minecraft/MultiMC/libraries/org/ow2/asm/asm-analysis/9.3/asm-analysis-9.3.jar
  D:/Games/Minecraft/MultiMC/libraries/org/ow2/asm/asm-commons/9.3/asm-commons-9.3.jar
  D:/Games/Minecraft/MultiMC/libraries/org/ow2/asm/asm-tree/9.3/asm-tree-9.3.jar
  D:/Games/Minecraft/MultiMC/libraries/org/ow2/asm/asm-util/9.3/asm-util-9.3.jar
  D:/Games/Minecraft/MultiMC/libraries/net/fabricmc/fabric-loader/0.14.8/fabric-loader-0.14.8.jar
  D:/Games/Minecraft/MultiMC/libraries/com/mojang/minecraft/1.8.9/minecraft-1.8.9-client.jar

Native libraries:
  D:/Games/Minecraft/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  D:/Games/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  D:/Games/Minecraft/MultiMC/libraries/tv/twitch/twitch-platform/6.5/twitch-platform-6.5-natives-windows-64.jar
  D:/Games/Minecraft/MultiMC/libraries/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-64.jar

Mods:
  [❌] anchiale-1.0.2+1.8.9.jar.disabled (disabled)
  [❌] atum-1.0.5+1.8.9.jar.disabled (disabled)
  [✔️] atum-1.0.7+1.8.9.jar
  [❌] forceport-mod-1.0.1.jar.disabled (disabled)
  [❌] optifabric-1.0.4+1.8.9.jar.disabled (disabled)
  [❌] OptiFine_1.8.9_HD_U_M5.jar.disabled (disabled)
  [❌] sleepbackground-3.6-1.8.x-1.12.x.jar.disabled (disabled)
  [❌] sleepbackground-3.7.1-1.8.x-1.12.x.jar.disabled (disabled)
  [❌] SpeedRunIGT-11.1+1.8.9.jar.disabled (disabled)
  [❌] standardsettings-1.2.1.1+1.8.9.jar.disabled (disabled)
  [❌] standardsettings-1.2.2+1.8.9.jar.disabled (disabled)
  [❌] standardsettings-1.2.2-pre1+1.8.9.jar.disabled (disabled)
  [❌] tab-focus-2.0.4+1.8.9.jar.disabled (disabled)
  [❌] toggle-sprint-1.8.9.jar.disabled (disabled)
  [❌] z-buffer-fog-1.2.jar.disabled (disabled)
  [❌] z-buffer-fog-1.3.jar.disabled (disabled)

Params:
  --username  --version 1.8.9 --gameDir D:/Games/Minecraft/MultiMC/instances/1.8.9_1/.minecraft --assetsDir D:/Games/Minecraft/MultiMC/assets --assetIndex 1.8 --uuid  --accessToken  --userProperties  --userType 

Window size: 854 x 480

Java Arguments:
[-XX:+UseZGC, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms1024m, -Xmx2048m, -Duser.language=en]


Minecraft process ID: 2600


Using onesix launcher.

[18:12:06] [main/INFO]: Loading Minecraft 1.8.9 with Fabric Loader 0.14.8
[18:12:06] [main/INFO]: Loading 4 mods:
	- atum 1.0.7+1.8.9
	- fabricloader 0.14.8
	- java 17
	- minecraft 1.8.9
[18:12:06] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/D:/Games/Minecraft/MultiMC/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
Completely ignored arguments: [--versionType, Fabric]
[18:12:07] [Client thread/INFO]: Setting user: tildejustin
[18:12:07] [Client thread/INFO]: (Session ID is token:<ACCESS TOKEN>:<PROFILE ID>)
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 9/21/22, 6:12 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'atum'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_1600.method_2921(class_1600.java:349)
	at net.minecraft.class_1600.method_5580(class_1600.java:310)
	at net.minecraft.client.main.Main.main(Main.java:124)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1666.method_5938()" because "this.field_6278" is null
	at net.minecraft.class_1600.method_6647(class_1600.java:637)
	at net.minecraft.class_389.<init>(class_389.java:18)
	at net.minecraft.class_351.<init>(class_351.java:26)
	at me.voidxwalker.autoreset.Atum.onInitialize(Atum.java:109)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 16 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_1600.method_2921(class_1600.java:349)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.class_1600.method_5580(class_1600.java:310)
	at net.minecraft.client.main.Main.main(Main.java:124)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.4.1, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 517996544 bytes (494 MB) / 1073741824 bytes (1024 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 4 total; -XX:+UseZGC -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx2048m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.8.9
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: ~~ERROR~~ NullPointerException: Cannot read field "field_10330" because "this.field_10318.field_3823" is null
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: ~~ERROR~~ NullPointerException: Cannot read field "field_7670" because "this.field_5044.field_3823" is null
	Current Language: ~~ERROR~~ NullPointerException: Cannot invoke "net.minecraft.class_1666.method_5942()" because the return value of "net.minecraft.class_1600.method_5579(net.minecraft.class_1600)" is null
	Profiler Position: N/A (disabled)
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# D:\Games\Minecraft\MultiMC\instances\1.8.9_1\.minecraft\crash-reports\crash-2022-09-21_18.12.08-client.txt
[18:12:08] [Client Shutdown Thread/INFO]: Stopping server
Process exited with code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 21 Sep 2022 18:12:16 -0400
Clipboard copy at: 21 Sep 2022 18:12:17 -0400
```
