### ISSUE TITLE
Crash on first time hitting the Atum button. [1.19, 1.18.2]

### ISSUE THREAD

**Issue by iinterp** [VoidXWalker/Atum#4]
The first time attempting to use Atum (clicking the gold boots) immediately crashes, but subsequent loads seem to work fine. It still crashes even if you add the mod after loading a world.

You can create a world the regular way without it crashing, but even after creating the world it still crashes if you try to use Atum.

I could reproduce on 1.19 and 1.18.2, but not 1.18.1.
Happened on MultiMC, PolyMC and the Vanilla Launcher.

`Java 17`
`Fabric Loader 0.14.8`
`Atum 1.0.5+1.19` or `1.0.5+1.18.2` (on seperate instances)
`No other mods`
```
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 30/06/2022, 18:28
Description: mouseClicked event handler

java.lang.NullPointerException: Cannot invoke "String.trim()" because "$$0" is null
	at net.minecraft.class_5285.method_40024(class_5285.java:190)
	at net.minecraft.class_5285.localvar$zzb000$setSeed(class_5285.java:521)
	at net.minecraft.class_5285.method_28024(class_5285.java)
	at net.minecraft.class_5292.method_41879(class_5292.java:226)
	at net.minecraft.class_7193.method_41865(class_7193.java:25)
	at net.minecraft.class_5292.method_28096(class_5292.java:226)
	at net.minecraft.class_525.method_41847(class_525.java:323)
	at net.minecraft.class_7196.method_41892(class_7196.java:247)
	at net.minecraft.class_525.method_2736(class_525.java:310)
	at net.minecraft.class_525.handler$zzc000$createDesiredWorld(class_525.java:773)
	at net.minecraft.class_525.method_25426(class_525.java:270)
	at net.minecraft.class_437.method_41843(class_437.java:391)
	at net.minecraft.class_437.method_25423(class_437.java:382)
	at net.minecraft.class_310.method_1507(class_310.java:1001)
	at net.minecraft.class_525.method_31130(class_525.java:161)
	at net.minecraft.class_442.handler$zzd000$init(class_442.java:532)
	at net.minecraft.class_442.method_25426(class_442.java:155)
	at net.minecraft.class_437.method_41843(class_437.java:391)
	at net.minecraft.class_437.method_25423(class_437.java:382)
	at net.minecraft.class_310.method_1507(class_310.java:1001)
	at net.minecraft.class_442.mde1b4e4$lambda$init$0$0(class_442.java:539)
	at net.minecraft.class_4185.method_25306(class_4185.java:40)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:120)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_442.method_25402(class_442.java:324)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1171)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.multimc.EntryPoint.listen(EntryPoint.java:127)
	at org.multimc.EntryPoint.main(EntryPoint.java:57)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_5285.method_40024(class_5285.java:190)
	at net.minecraft.class_5285.localvar$zzb000$setSeed(class_5285.java:521)
	at net.minecraft.class_5285.method_28024(class_5285.java)
	at net.minecraft.class_5292.method_41879(class_5292.java:226)
	at net.minecraft.class_7193.method_41865(class_7193.java:25)
	at net.minecraft.class_5292.method_28096(class_5292.java:226)
	at net.minecraft.class_525.method_41847(class_525.java:323)
	at net.minecraft.class_7196.method_41892(class_7196.java:247)
	at net.minecraft.class_525.method_2736(class_525.java:310)
	at net.minecraft.class_525.handler$zzc000$createDesiredWorld(class_525.java:773)
	at net.minecraft.class_525.method_25426(class_525.java:270)
	at net.minecraft.class_437.method_41843(class_437.java:391)
	at net.minecraft.class_437.method_25423(class_437.java:382)
	at net.minecraft.class_310.method_1507(class_310.java:1001)
	at net.minecraft.class_525.method_31130(class_525.java:161)
	at net.minecraft.class_442.handler$zzd000$init(class_442.java:532)
	at net.minecraft.class_442.method_25426(class_442.java:155)
	at net.minecraft.class_437.method_41843(class_437.java:391)
	at net.minecraft.class_437.method_25423(class_437.java:382)
	at net.minecraft.class_310.method_1507(class_310.java:1001)
	at net.minecraft.class_442.mde1b4e4$lambda$init$0$0(class_442.java:539)
	at net.minecraft.class_4185.method_25306(class_4185.java:40)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:120)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_442.method_25402(class_442.java:324)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_442
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1171)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.multimc.EntryPoint.listen(EntryPoint.java:127)
	at org.multimc.EntryPoint.main(EntryPoint.java:57)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2295)
	at net.minecraft.class_310.method_1514(class_310.java:753)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.multimc.EntryPoint.listen(EntryPoint.java:127)
	at org.multimc.EntryPoint.main(EntryPoint.java:57)

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.2, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 1553786176 bytes (1481 MiB) / 1992294400 bytes (1900 MiB) up to 2684354560 bytes (2560 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 2700X Eight-Core Processor         
	Identifier: AuthenticAMD Family 23 Model 8 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 2070 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1e84
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1179
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.60
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.60
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 39861.74
	Virtual memory used (MB): 20086.34
	Swap memory total (MB): 23552.00
	Swap memory used (MB): 503.55
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms256m -Xmx2560m
	Launched Version: 1.19
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 511.79, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 2700X Eight-Core Processor 
```

**Comment by iinterp** [comment]
Fixed in 1.1.0 for 1.18.2 but since 1.19 wasn't updated the issue still persists on 1.19.
